### ISSUE TITLE
cd hanging on linux

### ISSUE THREAD

**Issue by jubishop** [b4b4r07/enhancd#103]
I've got the exact same setup on linux and mac, yet on linux when i type "cd" and then enter, it just hangs.  when i look at `ps ax | grep enhancd` i see:

`gawk -f /usr/local/google/home/jubi/.zplugin/plugins/b4b4r07---enhancd/lib/reverse.awk`

as the hung enhancd process.  on mac, this works perfectly.  i wish i could figure out why it's failing on my linux box.  i love enhancd so much!  please let me know if there's any way you could help me diagnose my problem.  cheers.

**Comment by Sheemon7** [comment]
Same here
