### ISSUE TITLE
Preformance problem with fuzzy match

### ISSUE THREAD

**Issue by Vonfry** [b4b4r07/enhancd#109]
**Question**

Here are 5000 line in my enhancd.log file. I run `cd` and pop a fuzzy search by fzf immediately. 

But if I type a sub directory such as `cd b` , it is slow to pop a search tool.

If I run `cat <path>/enhancd.log | grep b`, it also returns immediately.

Is this a problem by enhancd self to check whole entries to match the subdirectories? Or I miss something to config it correctly?

By the way, is there a way to let me check the preformance such as verbose or time?

**Addition**

If I disable the fuzzy match by enhancd, the problem is fixed.

**Comment by b4b4r07** [comment]
It's likely to come from enhancd itself issue. I'm also thinking to improve enhancd performance. Currently enhancd may not be tuned well with huge log files.

I'm gonna do this later. Thanks for the report!
