### ISSUE TITLE
Fish support requires manually setting alias

### ISSUE THREAD

**Issue by nesl247** [b4b4r07/enhancd#11]
The fish script doesn't have anything in it for `ENHANCD_COMMAND`, which means we have to manually add an alias for `cd` to `enhancd` via `alias cd enhancd`.

**Comment by b4b4r07** [comment]
@nesl247 I'm sorry for the late update. The fish script don't support anything `ENHANCD_*` now.

**Comment by bucaran** [comment]
@babarot How about adding the fish port as a repo in fisherman and I can help you maintain it there? You would remain the only admin of course.

**Comment by nesl247** [comment]
I don't know how the fisherman stuff works, but I hope you refrain from making it only work with fisherman.

**Comment by bucaran** [comment]
@nesl247 On the contrary, the [snippet] format is a new fish-shell feature in 2.3, see [here](https://github.com/fish-shell/fish-shell/pull/2498) if you want to learn more.



With fisherman you have _true_ framework independence, as . Even if you are using the old oh-my-fish plugins, fisherman transforms them into the new fish-shell snippet :)

@b4b4r07

**Comment by nesl247** [comment]
@bucaran Ok cool. I didn't know about the snippet thing, and had just wanted to make sure this wasn't going to depend on something fisherman specific. With the way you wrote the bit about the snippet it sounded like it was a fisherman feature.

Thanks for the info!

**Comment by bucaran** [comment]
@nesl247 Yes, you are right, I can come across as annoying when talking about fisherman, but I only hope to make enhancd available to fisherman users and help @b4b4r07 better support it.

**Comment by nesl247** [comment]
Not to derail this any further, but I didn't mean you were coming across annoying at all, just unclear.

Thanks again.

**Comment by b4b4r07** [comment]
github.com/fisherman/enhancd

**Comment by mustaqimM** [comment]
@b4b4r07 How do I use 'enhancd' with `fish`? The linked repo is empty

**Comment by b4b4r07** [comment]
It's not developed yet. So we cannot use it now. (Moreover I cannot write fish script...)
