### ISSUE TITLE
Add git root

### ISSUE THREAD

**Issue by hoshsadiq** [b4b4r07/enhancd#110]
**Describe the feature you'd like**
Add an extra option entry to the list to allow to go to the git root of a directory. Ideally towards the top (possibly after the last directory). This should of course only show if you're inside a git repository (`git rev-parse --is-inside-work-tree`). The git root can be found using `git rev-parse --show-toplevel`

**Describe alternatives you've considered**
https://github.com/mollifier/cd-gitroot/

**Additional context**
N/A

**Comment by b4b4r07** [comment]
Thank you for the comment.

This should be included in the default list?

e.g.

```console
deep-dir@git-repo$ cd
/path/to/git_root
/old/directory/1
/old/directory/2
/old/directory/3
/old/directory/4
```

**Comment by hoshsadiq** [comment]
I would say yes, it should be.

**Comment by b4b4r07** [comment]
OK, I'm gonna try to add this feature

**Comment by hoshsadiq** [comment]
Just realised I never closed this. This has been working well for me! Thanks!
