### ISSUE TITLE
cd <TAB> brings  standard menuselect in zsh instead of fuzzy search

### ISSUE THREAD

**Issue by seflue** [b4b4r07/enhancd#118]
**Question**
When I do `cd <TAB>` in my zsh, I get just the normal zsh menuselect preview of the current folder. Only when I do `cd ..<CR>` or `cd -<CR>`, I get a fuzzy search, but for the latter only on already visited folders. I'm using zinit as plugin manager and my zinit config for enhancd looks like the following:

```
zinit ice wait lucid atload"zicompinit; zicdreplay" blockf 
zinit light b4b4r07/enhancd
```

I also use vi-mode in zsh. But when I switch to emacs-mode with set -o emacs, the behavior is the same as described above.

**Comment by seflue** [comment]
Ok, sorry for the question, I found just out by myself: I did forget to set `ENHANCD_COMPLETION_BEHAVIOR=list`

**Comment by sinapis** [comment]
I did set ENHANCD_COMPLETION_BEHAVIOR, but still have tab completion. using fish

**Comment by b4b4r07** [comment]
This feature may be removed #191 soon.

**Comment by b4b4r07** [comment]
PR has been merged so I think this issue has no longer needed
