### ISSUE TITLE
Odd behaviour with zsh-autosuggestions

### ISSUE THREAD

**Issue by gipert** [b4b4r07/enhancd#121]
**Question**
I have zsh-autosuggestions installed and configured with a custom color for the auto-suggested text (grey). Since I have installed enhancd this color suddenly changes to the foreground color when completing with `Tab`. The following screencast demonstrates the issue:

[![asciicast](https://asciinema.org/a/td5Kn6pNMFMIxifDtuPm76R8z.svg)](https://asciinema.org/a/td5Kn6pNMFMIxifDtuPm76R8z)

Ideas on why this is happening?

**Comment by b4b4r07** [comment]
I'm sorry it's difficult to grab your situation and to reproduce it on my environment... Currently it's difficult to support this. So I'm gonna close this once. I want to wait another persons to face this similar odd case.
