### ISSUE TITLE
Why auto remove unused source files??????

### ISSUE THREAD

**Issue by aQuaYi** [b4b4r07/enhancd#123]
**What did you expect to happen?**
init.sh do not delete fish source files.
init.fish do not delete bash/zsh source files.

**What actually happened?**
I use both zsh and fish. After I change back the last shell, It will remind me init source file does not exist.

**Comment by aQuaYi** [comment]
https://github.com/aQuaYi/prezto/tree/master/plugins/a-enhancd

I use enhancd as a submodule in my own prezto fork.

**Comment by akirak** [comment]
I find this pretty annoying too. I use this plugin via Nix, and since Nix stores all source files in read-only directories, a bunch of the following message lines are shown every time I open a shell:

> rm: cannot remove '/nix/store/clj3xyy9h660pan225fmy9zlz3w2wib7-source/functions/_enhancd_flag_is_default.fish': Read-only file system

**Comment by akirak** [comment]
In Nix, I've solved this issue with the following workaround:

```nix
          src =
            let
              origSrc = pkgs.fetchFromGitHub {
                owner = "b4b4r07";
                repo = "enhancd";
                rev = "f0f894029d12eecdc36c212fa3ad14f55468d1b7";
                sha256 = "1qk2fa33jn4j3xxaljmm11d6rbng6d5gglrhwavb72jib4vmkwyb";
                # date = 2020-02-11T14:27:32+09:00;
              };
              drv = pkgs.stdenv.mkDerivation {
                name = "copy-enhancd";
                src = origSrc;
                buildPhase = "";
                installPhase = ''
                mkdir -p $out
                cp -ra -t $out $src/src $src/lib $src/config.ltsv $src/init.sh
                '';
              };
            in drv;
```

That is, don't install the fish sources that are to be removed by the script. This works in zsh.

**Comment by jorgebucaran** [comment]
Fixed in https://github.com/b4b4r07/enhancd/commit/7085570557da3bbed219d103cf53102babba4243. Please update to the latest `enhancd` and let us know if you still have any issues. 👋
