### ISSUE TITLE
help does not work

### ISSUE THREAD

**Issue by zhu** [b4b4r07/enhancd#124]
**What did you expect to happen?**
Describe what you expected to happen here.

**What actually happened?**
Describe what actually happened here.
help options is empty

**Output**
```text
> cd --help
Usage: cd [OPTIONS] [dir]

OPTIONS:






Version: 2.2.4
```

**Additional context**
OS: Debian 10 in wsl
Shell: fish

**Comment by zhu** [comment]
In https://github.com/b4b4r07/enhancd/blob/f0f894029d12eecdc36c212fa3ad14f55468d1b7/lib/help.awk#L48 ,awk index is 1 based, `0` should change to `1`. My debian has mawk which work different with gawk or awk when start index is 0.
In https://github.com/b4b4r07/enhancd/blob/f0f894029d12eecdc36c212fa3ad14f55468d1b7/config.ltsv#L2 , fish do not support `[[`.

**Comment by jorgebucaran** [comment]
Fixed in https://github.com/b4b4r07/enhancd/commit/7085570557da3bbed219d103cf53102babba4243. Please update to the latest `enhancd` and let us know if you still have any issues. 👋
