### ISSUE TITLE
not working on WSL

### ISSUE THREAD

**Issue by Light-dev-mac** [b4b4r07/enhancd#130]
The enhancd don't work  on WAL.
The path seems to go through well.
(I confirmed with the which command)

Please help me .

**Comment by fogx** [comment]
works for me in wsl. not sure what your issue is tbh

**Comment by sinapis** [comment]
Works for me in WSL as well

**Comment by b4b4r07** [comment]
help wanted. I don't have WSL environment..

**Comment by b4b4r07** [comment]
I don't have enough resources to support this now..! Closing
