### ISSUE TITLE
Dot suggestion does not work

### ISSUE THREAD

**Issue by fnpen** [b4b4r07/enhancd#131]
**What did you expect to happen?**
I want to see UI choose options to go subfolders in the current folder or use fuzzy-search

**What actually happened?**
Nothing, I am in the current folder.

**Output**
```text
cd .
```

**Additional context**
macOS, iTerm, 
fish, version 3.1.2

![image](https://user-images.githubusercontent.com/31767378/84745198-e772e300-afbc-11ea-8d72-b9a65872cff0.png)

**Comment by jorgebucaran** [comment]
@fnpen This should be fixed in the latest Enhancd. Please upgrade and let us know if you still have any issues. 👋
