### ISSUE TITLE
What am I doing wrong here? Need clearer install instructions.

### ISSUE THREAD

**Issue by bassamanator** [b4b4r07/enhancd#138]
**Question**
I've cloned to .enhancd. Then I did 
```
source ./init.sh
```

**Considerations**
Doesn't seem to be working :/
I'm on zsh

**Comment by vpishuk** [comment]
I'm on regular bash. It doesn't work for me as well.

**Comment by gazorby** [comment]
Hi @bassamanator @vpishuk this should be fixed in 7085570 can you update to the latest enhancd?

**Comment by b4b4r07** [comment]
Getting stale and maybe fixed now. Closing but feel free to let me know if still have something
