### ISSUE TITLE
ENHANCD_DOT_ARG=... not working?

### ISSUE THREAD

**Issue by fogx** [b4b4r07/enhancd#140]
**What did you expect to happen?**
i wanted to set `...` to be the enhanced dot arg, so that i can do a normal `..` but still use the functionality. But it seems like `...` is being overwritten? In effect, `...` just goes up 2 folders as before enhancd. Not sure where the triple dot command is coming from though (ZSH or oh-my-zsh?)

Is there a way to make this work regardless?

**Comment by ress997** [comment]
This must be set before loading enhancd.

Try it without loading enhancd.
```shell
export ENHANCD_DOT_ARG='...'
source ./init.sh
```

**Comment by fogx** [comment]
hey @ress997 thanks for your reply. I just tried that
```
export ENHANCD_DOT_ARG='...'
source ~/.oh-my-zsh/enhancd/init.sh
```
 but it  does not seem to work

**Comment by d3dave** [comment]
`...` is aliased by oh-my-zsh:
```zsh
> type '...'
... is a global alias for ../..
```
See https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/directories.zsh#L6

**Comment by fogx** [comment]
thanks for your insight @d3dave .
So if i unalias `...` like this it should work right?
```
source $ZSH/oh-my-zsh.sh
unalias '...'
ENHANCD_DOT_ARG='...'
ENHANCD_DIR=~/.oh-my-zsh/enhancd
ENHANCD_FILTER=fzf
source ~/.oh-my-zsh/enhancd/init.sh
```
but the command still does not seem to be registered:
`zsh: command not found: ...`
I would have thought that enhancd overwrites the `...` alias.

**Comment by d3dave** [comment]
`enhancd` doesn't alias `$ENHANCD_DOT_ARG`. It's used when `cd` is invoked explicitly, like `cd ...`. You're probably looking for `alias ...='enhancd ..'` or something similar.

**Comment by b4b4r07** [comment]
![Screenshot 2023-03-31 at 2 58 53](https://user-images.githubusercontent.com/4442708/228923813-4ef11a88-f1f6-4bd4-ae49-5b1da0dc57ad.png)

Looks working! I'm closing this issue once because this issue is getting stale now but feel free to let me know if you have still some problems.
