### ISSUE TITLE
Customizing keybindings for enhancd menu navigation.

### ISSUE THREAD

**Issue by tekhnee** [b4b4r07/enhancd#150]
**Question**
Can I use `bindkey` to customize the `enhancd` menu navigation controls?

If so, what is the appropriate keymap?

I'd like to use <kbd>Alt</kbd>-<kbd>J</kbd> and <kbd>Alt</kbd>-<kbd>K</kbd> for down and up, respectively, also remapping <kbd>Ctrl</kbd>-<kbd>J</kbd> to accept the highlighted option.

Thank you.

**Comment by ress997** [comment]
enhancd menu navigation is supposed to be provided by visual filters such as fzy and peco.
- https://github.com/b4b4r07/enhancd#references

For example, in [fzf](https://github.com/junegunn/fzf), you can freely set key bindings by using `--bind` option to `$FZF_DEFAULT_OPTS`.

**Comment by tekhnee** [comment]
Thanks for the tip!
