### ISSUE TITLE
got err when run init.sh

### ISSUE THREAD

**Issue by beauji1116jbn** [b4b4r07/enhancd#153]
**What did you expect to happen?**
I don't know, I guess should not see an error at least

**What actually happened?**
i couldn't install this by zplug, tried, but didn't work, so i tried to install manually but got this err when i run init.sh
![image](https://user-images.githubusercontent.com/57028822/106925193-ced15c00-674a-11eb-90c4-9871e11b0bb8.png)

**Output**
```text
enhancd/src/completion.zsh: line 149: syntax error near unexpected token `('
enhancd/src/completion.zsh: line 149: `  [[ $binding =~ 'undefined-key' ]] || ENHANCD_COMPLETION_DEFAULT=$binding[(s: :w)2]'
```

**Comment by beauji1116jbn** [comment]
my mistake

**Comment by jorgebucaran** [comment]
No problem. Glad you got it sorted out.

**Comment by HagaSpa** [comment]
> enhancd/src/completion.zsh: line 149: syntax error near unexpected token `('
enhancd/src/completion.zsh: line 149: `  [[ $binding =~ 'undefined-key' ]] || ENHANCD_COMPLETION_DEFAULT=$binding[(s: :w)2]'


I got same error.
The cause was that I wrote `source ~/enhancd/init.sh` twice in my `.zshrc`.
FYI.
