### ISSUE TITLE
cd <tab> in fish?

### ISSUE THREAD

**Issue by robdecker** [b4b4r07/enhancd#154]
In fish shell, is there any way to make `cd <tab>` trigger enhancd?

**Comment by jorgebucaran** [comment]
What about `bind \t enhancd`?

**Comment by robdecker** [comment]
Yes that works, but I guess I'm looking for `<tab>` to only trigger enhancd when the commandline starts with `cd` or `cd `(with a space after cd). Is this possible? Thanks!

**Comment by jorgebucaran** [comment]
Could you try this?

```fish
bind \t '
    commandline --paging-mode && down-or-search || 
    switch (commandline)
        case cd{," "}
            enhancd
        case \*
            commandline --function complete
    end
'
```

**Comment by jorgebucaran** [comment]
I hope that does what you need. It's working for me, so I think we're done here. 😁

**Comment by robdecker** [comment]
Hi @jorgebucaran, it does work (in that it triggers enhancd), but when the fzf list of paths opens and I choose one, that path isn't returned to the command line. The command line only shows the `cd` that I had typed prior to hitting `<tab>`.

**Comment by jorgebucaran** [comment]
You can use [`commandline`](https://fishshell.com/docs/current/cmds/commandline.html) to get and set the command line buffer.

```fish
commandline --insert foo/bar
```

will insert "foo/bar" at the current cursor position. Now you just need to figure out how to print the path you chose, and modify my solution above to set the command line buffer to it.

**Comment by robdecker** [comment]
OK, thanks for your help.
