### ISSUE TITLE
__enhancd::sources::default() doesn't handle properly spaces in names

### ISSUE THREAD

**Issue by m-dhooge** [b4b4r07/enhancd#158]
**What did you expect to happen?**
When I issue a single `cd` command, I expect folders with spaces in their names to be correctly displayed.

**What actually happened?**
Folders names are split on spaces in addition to EoL.

**Additional context**
If I replace the `default()` function by the following code, it works as expected…

```
__enhancd::sources::default()
{
    __enhancd::history::list | __enhancd::filter::interactive
}
```

Thanks

**Comment by d3dave** [comment]
+1 I encountered the same issue. Fix is available in #148.

**Comment by m-dhooge** [comment]
The PR works for me. Thanks

**Comment by vFones** [comment]
any news on when this will be merged?

**Comment by b4b4r07** [comment]
Sorry for late reply. It has been already merged
