### ISSUE TITLE
occasional high cpu usage + filling up hard drive

### ISSUE THREAD

**Issue by jedahan** [b4b4r07/enhancd#16]
Once out of about 10 times I use cd::cd, my cpu usage goes super high, and enhancd.log fills up whatever space i have left on my hard drive. When I hear the fans spin, I have to killall cat to go back to normal. In addition, while this is going on, any other shell I try cd in, it hangs. How can I help debug where my issue is?

**Comment by b4b4r07** [comment]
Thank you for your report. Because I want to know more, please tell me the steps to reproduce.

**Comment by jedahan** [comment]
OK I was doing nothing, I just have one terminal window open, and was browsing online, and got the message 'your startup disk is full'.

I ran `sudo lsof -s | awk '$5 == "REG"' | sort -n -r -k 7,7 | head -n 1`

and got:

`tail      84457         jedahan    3r      REG                1,3 28359110656 6794235 /Users/jedahan/.enhancd/enhancd.log`

but when i try and `ls -al ~/.enhancd/enhancd.log` that file does not exist.

When I `kill 84457`, all is well, and I get my 26gb back.

**Comment by jedahan** [comment]
My dotfiles are github.com/jedahan/dotfiles , if that helps

**Comment by jedahan** [comment]
It happened again. After I killed the process, I went to a git repository, added some file and commited, and then tried to `cd .some/sub/directory`. Instantly went to 100% cpu usage and growing lsof file that I cannot cat.

**Comment by jedahan** [comment]
Now when I kill it, it respawns :(

**Comment by jedahan** [comment]
I am trying to modify https://github.com/sindresorhus/pure/blob/master/pure.zsh#L226 and https://github.com/sindresorhus/pure/blob/master/pure.zsh#L239 to see if those are issues, or using another prompt.

**Comment by b4b4r07** [comment]
Thank you for your report!

As far as I know, `pure`'s `cd` command is the causes. I will try to prevent interference of `enhancd` with other plugins. Thanks.
