### ISSUE TITLE
cd .. fails to switch to parent folder when parent folder contains non-alphanumerics like "+" character

### ISSUE THREAD

**Issue by mouroutzoglou** [b4b4r07/enhancd#160]
**What did you expect to happen?**
Change directory through the "cd .." command

**What actually happened?**
Didn't change directory.
In fact, I think a cd command was executed but to the folder I'm currently in.

**Reproduction**
```
> cd ~
> mkdir a+b
> cd a+b
> mkdir c
> cd c
> cd ..
```
Choose ~/a+b from fzf window and press enter
`> pwd`
It prints ~/a+b/c instead of ~/a+b
`> cd ..`
Choose ~ from fzf window and press enter
`> pwd`
It prints ~

**Additional Information**
zsh version: 5.8
enhancd version: master
enhancd installed through zinit
grep version: 3.1
awk version: 20180827
fzf version: 0.27.2

**Comment by b4b4r07** [comment]
![](https://user-images.githubusercontent.com/4442708/227732389-f6d01b50-b033-4ddd-aa7c-68dd21abcb36.png)

Maybe fixed (not happen).
