### ISSUE TITLE
Allow for hooking into enhancd

### ISSUE THREAD

**Issue by hoshsadiq** [b4b4r07/enhancd#167]
**Describe the feature you'd like**
It would be nice to allow for hooking into enhancd in some way. Reason is for me specifically we have a specific folder structure that defines the name said for structure. Said name is used in a lot of places, so I tend to copy this name, then type in `cd |` (where `|` is the cursor), then paste, then replace the underscores with `/` one at a time, then press enter.

For example, given the directory structure:
```
root
  - main
    - level1
      - level2
```
The directory `root/main/level1/level2` has a "name" called `level1_level2`.

What I'd like is to just paste `level1_level2` and enhancd passes that into a hook I've written, and if it's resolved into a directory, it `cd` into the resolved directory. Currently I paste `level1_level2`, then manually go through it and change `_` with `/`.

**Describe alternatives you've considered**
Overload enhancd, but this can be tempermental and a little more nuanced.

**Additional context**

**Comment by b4b4r07** [comment]
@hoshsadiq 

Sorry for the late reply.

enhancd is not a directory bookmarking tool. So currently it's difficult to add this feature
