### ISSUE TITLE
fish shell pipe to cd fix

### ISSUE THREAD

**Issue by DevAtDawn** [b4b4r07/enhancd#169]
Interested in making a pull request for:

[](https://github.com/b4b4r07/enhancd#issues)Issues
    Fish version
        Because of how fish piping works, it's not possible to pipe to cd like : ls / | cd
        
got the base functionality working already if anyone wants to test it  https://github.com/DevAtDawn/fish-shell-pipe-to-cd

**Comment by DevAtDawn** [comment]
#170

**Comment by b4b4r07** [comment]
Currently I didn't support fish actively because I'm not fish user. So I'm sorry but I cannot support this case.
