### ISSUE TITLE
native cd completion

### ISSUE THREAD

**Issue by CircleCode** [b4b4r07/enhancd#172]
**Question**
is there a way to keep `\cd` native completion for `<tab>`?

**Considerations**
I have the feeling that I used to do `cd D<tab>` and to have native completion like with `\cd D<tab>`
But now (I don't know when things changed), `cd D<tab>` brings nothing

Note: I don't want `ENHANCD_COMPLETION_BEHAVIOR`, I want to have enhanced triggered only when I do `cd<enter>`

**Comment by b4b4r07** [comment]
@CircleCode 

Sorry for the late reply. Thank you. I did `cd D<tab>` and got the following result:

I think it's almost what you want. What do you want on that action? (maybe I still may not be able to understand what you said.)

![](https://user-images.githubusercontent.com/4442708/227731614-2b41620a-af42-4b03-ab0f-8a2cd55a0c40.png)

**Comment by CircleCode** [comment]
@b4b4r07 Thanks for the update. On my side, it's still not working :-(

You can see the replay here: https://asciinema.org/a/FqTrA8MqMxBTInBrAe2vmBCr7

notes:
- around 00:10, I'm using `ba<tab>` with no effect,
- at 00:12, I'm using `baz<tab>` which returns the ` -- no matches found -- `

Any idea of what I can provide or dig to help debugging?

**Comment by b4b4r07** [comment]
Oh thank you for sharing the details! I'll work on this to fix. I'm thinking to remove all completion feature from enhancd at all now...

because:

- Maintenance cost is high
- Better to use native cd completion

Anyway I'll work on this in this weekend

**Comment by CircleCode** [comment]
Thanks :-)

By the way, what were the completion features specific to enhancd and not available in native cd completion?

**Comment by b4b4r07** [comment]
@CircleCode 

Can you try this branch? https://github.com/b4b4r07/enhancd/pull/191

>By the way, what were the completion features specific to enhancd and not available in native cd completion?

Almost same as https://github.com/changyuheng/zsh-interactive-cd's one! But I'm now thinking it's better to use this plugin, not enhancd's completion feature.

**Comment by b4b4r07** [comment]
@CircleCode 

Nice, thank you for the survey! 

>The problem was that zsh resolves the alias before launching completion (because the option COMPLETE_ALIASES is not enabled on my env).

Ah,.. I see. Nice catch, so super thanks. Thus it means we don't need to merge this PR, right..? Hmm. But actually I have already no much enough motivation to keep this completion feature now lol. So I'm thinking to merge this anyway.

On the other hands, we may need to think how we should solve this problem on enhancd.

**Comment by CircleCode** [comment]
> Thus it means we don't need to merge that PR, right..?

right

> Hmm. But actually I have already no much enough motivation to keep this completion feature now lol.

I get it, and as said previously, on my side, I do not expect this kind of completion from enhancd, so I won't really persuade you to keep this feature!

> On the other hands, we may need to think how we should solve this problem on enhancd.

Which problem are you talking about? I cannot anymore see a problem: on the branch with completion, we need to load it after the call of compinit (this is a user issue…), and on the branch without completion, either defining `setopt COMPLETE_ALIASES` or aliasing the completion like suggested in a previous comment makes it work like a charm!

**Comment by b4b4r07** [comment]
I've merged that PR. Thank you!

>Which problem are you talking about? I cannot anymore see a problem: on the branch with completion, we need to load it after the call of compinit (this is a user issue…), and on the branch without completion, either defining setopt COMPLETE_ALIASES or aliasing the completion like suggested in a previous comment makes it work like a charm!

Thank you for the summary. What I wanted to say is that I might be better to mention about it in README or something. But this issue is helpful for those who's facing the same issue even if no annotations so I'll guide them to this issue at that time.

Anyway thank you for raising issue and investigating why this happens!
