### ISSUE TITLE
Is this a bug? Unexpected behavior is occurred when running 'cd ..'

### ISSUE THREAD

**Issue by jmatsu** [b4b4r07/enhancd#18]
It seems that rindex() in awk script is wrong.  
Current rindex() checks whether one string contains another string or not.

Is it correct behavior? Or just a bug?

I faced an issue. Following,

```sh
mkdir -p /foo/com.foo/baz
cd /foo/com.foo/baz
cd .. # then, select 'foo'
# expect $(pwd) == "/foo"
# actual $(pwd) == "/foo/com.foo"
```

**Comment by b4b4r07** [comment]
Thank you for your report.

Great job :+1:
This is a bug. Your PR is correct behavior.
