### ISSUE TITLE
Gnu awk (gawk) related errors are printed on invocation

### ISSUE THREAD

**Issue by mrincredibleu** [b4b4r07/enhancd#189]
**What did you expect to happen?**
Matching directories should be listed.

**What actually happened?**
Errors are printed

**Output**
```text
$ cd lib
gawk: /Users/mrincredible/.zinit/plugins/b4b4r07---enhancd/functions/enhancd/lib/fuzzy.awk:8: warning: escape sequence `\/' treated as plain `/'
gawk: /Users/mrincredible/.zinit/plugins/b4b4r07---enhancd/functions/enhancd/lib/fuzzy.awk:9: (FILENAME=- FNR=3) fatal: attempt to use scalar `lines' as an array
no entry
```

**Additional context**
The error seems to be related to a recent change:

https://github.com/b4b4r07/enhancd/blob/e27cf951aa737569165bd608e442abec34b19165/functions/enhancd/lib/fuzzy.awk#L6-L10

I am using Gnu Awk 5.2.1, API 3.2 and github.com/b4b4r07/enhancd @ e27cf951aa737569165bd608e442abec34b19165

**Comment by b4b4r07** [comment]
Thank you for the report. I'll work on this

**Comment by b4b4r07** [comment]
@mrincredibleu 

I merged the patch and it was fixed on latest master branch!

**Comment by mrincredibleu** [comment]
すごい速いな〜！どうもありがとう！
