### ISSUE TITLE
Seems to break tmux initial directory

### ISSUE THREAD

**Issue by felixSchl** [b4b4r07/enhancd#20]
It appears that when I start a new tmux session while having loaded `enhancd`, the initial working directory is not set properly - it will always be '~'. I have not done any further diagnosing yet. I am on OSX.

**Comment by b4b4r07** [comment]
Thank you for your report. Could you inform me in details?

**Comment by felixSchl** [comment]
hm, I tried to create a docker image to reproduce this but couldn't... I'll close this and do more research. It's probably either due to my config files or me being on OSX...
