### ISSUE TITLE
How to use fd

### ISSUE THREAD

**Issue by linwaytin** [b4b4r07/enhancd#208]
**Question**
How to use `fd` instead of `find`

**Considerations**
Is there an option to change the `find` to `fd`? The README mentions this possibility, but doesn't say how to do it. Thank you.

**Comment by b4b4r07** [comment]
Thank you for trying this app.

Automatically fd is used if installed.

**Comment by linwaytin** [comment]
Somehow I saw error messages with `find`. Is this just wording? I also feel `cd .` is slow so I think `fd` is being used.

**Comment by b4b4r07** [comment]
Could you show me the screenshot of that error message?

**Comment by linwaytin** [comment]
The message is like `find: 'path-to-some-folder': No such file or directory`. I have `fd` installed, so I'm not sure which program is used.

**Comment by vlaw** [comment]
> Could you show me the screenshot of that error message?

<img width="326" alt="image" src="https://user-images.githubusercontent.com/56830/234255605-aae55332-0441-4620-b7f6-d6977ca1f228.png">

**Comment by vlaw** [comment]
> > Could you show me the screenshot of that error message?
> 
> <img alt="image" width="326" src="https://user-images.githubusercontent.com/56830/234255605-aae55332-0441-4620-b7f6-d6977ca1f228.png">

```shell
__enhancd::filepath::walk() {
	local -a dirs

	# __enhancd::filepath::get_parent_dirs does not return $PWD itself,
	# so add it to the array explicitly
	set -x # <- HERE
	dirs=("$PWD" "$(__enhancd::filepath::get_parent_dirs "${1:-${PWD}}")")
	set +x

	for dir in "${dirs[@]}"; do
		command find "$dir" -maxdepth 1 -type d -name '\.*' -prune -o -type d -print
	done
}
```

```sh
+__enhancd::command::awk:5> awk -f /Volumes/Source/code/github.com/b4b4r07/enhancd/functions/enhancd/lib/step_by_step.awk -v 'dir=/Volumes/Source/code/github.com/LazyVim/LazyVim'
+__enhancd::filepath::walk:6> dirs=( /Volumes/Source/code/github.com/LazyVim/LazyVim $'/Volumes/Source/code/github.com/LazyVim\n/Volumes/Source/code/github.com\n/Volumes/Source/code\n/Volumes/Source\n/Volumes\n/' )
```

I believe the`$` and `\n` in the last line is not as expected.
The `awk`  (or `gawk`) command result is separated line by line.

**Comment by b4b4r07** [comment]
Ah, maybe I got it. Related to #209, so closing this issue to make the issue into one. Thank you for raising issue
