### ISSUE TITLE
Provide options to disable `..` and `-`

### ISSUE THREAD

**Issue by loggerhead** [b4b4r07/enhancd#22]
Is there exists any config to disable `..` and `-`? I found it is inconvenience for me because I frequent use `cd ..` and `cd -`.

**Comment by b4b4r07** [comment]
At the moment, it's impossible. I might implement this feature in near future.

**Comment by loggerhead** [comment]
Works, good job!

**Comment by b4b4r07** [comment]
Implemented. Please update enhancd. Thanks!
