### ISSUE TITLE
enhancd is compatible with anyframe's cd commands ?

### ISSUE THREAD

**Issue by takanabe** [b4b4r07/enhancd#23]
Hi ! I now try to use enhancd and anyframe with zplug.
Accrording to your zplug example, both enhancd and anyframe looks compatible.

But after installing enchancd, `cdr` and `cd-ghq-repository` of anyframe fail to execute with following error.

```
: no such file or directory
```

Is this occurred only my environment ?

**Comment by b4b4r07** [comment]
Hi, thank you for using zplug. Those are thoroughly examples. Please tell me your zshrc.

**Comment by b4b4r07** [comment]
I'll close this issue because this is always open. Please let me know if you have any problem.
