### ISSUE TITLE
It does not work in zsh theme setting

### ISSUE THREAD

**Issue by shimizumasaru** [b4b4r07/enhancd#26]
zplug "caiogondim/bullet-train-oh-my-zsh-theme"
do not work when you set .
To work with the stop setting .
Happy and use my favorite theme .

**Comment by b4b4r07** [comment]
Hi, what do you mean? How do enhancd relate to this issue?

**Comment by shimizumasaru** [comment]
I'm sorry if my misunderstanding .
Using the "zplug" in my zsh introduced the "enhancd" and "theme". 
In this case, "enhancd" it did not work correctly .
So , if you remove the "theme" was introduced in zplug "enhancd" was operating correctly .
p.s.
Is this one of the zplug or enhancd or theme is the problem?

**Comment by b4b4r07** [comment]
probably fixed
