### ISSUE TITLE
enhancd randomly print some log information

### ISSUE THREAD

**Issue by hatelove85911** [b4b4r07/enhancd#27]
sometimes when I change to a directory, I'll get some log like below, how can I disable it or it's a bug??

![1__zsh](https://cloud.githubusercontent.com/assets/2359121/13277934/563198f2-db07-11e5-985c-f2034b9cf8fe.png)

**Comment by b4b4r07** [comment]
Please tell me your problem more details because I cannot reproduce this in my environment.

**Comment by b4b4r07** [comment]
I'll close this issue because this is always open. Please let me know if you have any problem.
