### ISSUE TITLE
Variable declaration (dup)

### ISSUE THREAD

**Issue by b4b4r07** [b4b4r07/enhancd#28]
For the general enhancd users, `ENHANCD_LOG` does not need. 

ja twitter.com post:

- https://twitter.com/ress997/status/713424741965496320
- https://twitter.com/ress997/status/713424940788109312
- https://twitter.com/ress997/status/713425588594151424

**Comment by b4b4r07** [comment]
Fixed.

**Comment by 39e** [comment]
Twitter の方でも報告させていただきましたがまた同じような現象が起きています

<img width="599" alt="ss 2016-05-24 3 49 33" src="https://cloud.githubusercontent.com/assets/15976255/15481050/9772e80a-2163-11e6-9c14-3fb1166f4e2e.png">
