### ISSUE TITLE
Case-insensitive autocomplete?

### ISSUE THREAD

**Issue by aroman** [b4b4r07/enhancd#33]
Thanks for this great module! I am used to and greatly enjoy being able to case-insensitively autocomplete directory names. e.g. if I am in `~` which has a `Developer` folder, if I type `cd dev<tab>`, it'll autocomplete to `cd Developer/`.

Unfortunately, enhancd breaks this case-insensitive autocomplete. Would it be possible for enhancd to support this somehow? I'd be happy to see about adding support myself if you tell me it's possible/desirable :)

**Comment by b4b4r07** [comment]
@aroman Thank you for your suggestion. 

I'm considering your request. Please wait until next week.

**Comment by stevenjlho** [comment]
+1

**Comment by b4b4r07** [comment]
@aroman @stevenjlho Sorry for late! Please try it out. Fixed probably

**Comment by stevenjlho** [comment]
It seems does not work in macOS Sierra

**Comment by b4b4r07** [comment]
What situation?

**Comment by stevenjlho** [comment]
When i type  `cd vagrant`, the console show below message
![qq20161019-0](https://cloud.githubusercontent.com/assets/523963/19503850/ff53d228-95e8-11e6-845b-8dfaeb8929cc.png)

But I think it should be only show this message `/Users/stevenjlho/Project/DevOps/Vagrant/.vagrant`

**Comment by b4b4r07** [comment]
I got, understood. Thanks. Please try `case-insensitive` branch.

**Comment by b4b4r07** [comment]
Please set `ENHANCD_USE_FUZZY_MATCH=0`

**Comment by stevenjlho** [comment]
It works perfectly, thanks.

**Comment by b4b4r07** [comment]
Merged, thanks.
