### ISSUE TITLE
ENHANCD_FILTER queried in loading time and introduces a zshrc load order bug

### ISSUE THREAD

**Issue by ninrod** [b4b4r07/enhancd#36]
I'm getting `fzf-tmux:fzf: Invalid value as ENHANCD_FILTER`

I'm using zplug on my [.zshrc](https://github.com/ninrod/dotfiles/blob/master/dot/zshrc)
```sh
source ~/.zplug/init.zsh
zplug "b4b4r07/enhancd", use:init.sh
```

`fzf-tmux` and `fzf` are perfectly fine on my system.

If I don't define `ENHANCD_FILTER` I also get and error:

```sh
# I've set ENHANCD_COMMAND=d
$ d
fzf-tmux:fzf:peco:fzy:percol:gof:pick:icepick:sentaku:selecta: Invalid value as ENHANCD_FILTER
$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.0.0)
```

**Comment by ninrod** [comment]
it was a zshrc load order issue.

**Comment by osdf** [comment]
I have the same issue but can't figure out how it relates to a zshrc load issue. Could you explain your solution? Muito obrigado!

**Comment by ninrod** [comment]
Hi. Surely I can. 

You have to make sure you have setup correctly your filter before the line:

`zplug "b4b4r07/enhancd", use:init.sh` in your zshrc.

In my specific case, I use `fzf-tmux` as my main filter. And the section that configures `fzf` was sitting after the `enhancd` loading instruction. I was suspecting of that and when I managed to swap those configurations, the problem was solved.

**Comment by ninrod** [comment]
In retrospect, maybe that's a enhancd bug. Or at least we could ask babaroth for a documenting section explaining this configuration? Makes sense? I think I'll reopen the issue based on that.

**Comment by osdf** [comment]
Thanks @ninrod! Moving the fzf config before the zplug block resolved the issue. True, having fzf append the configuration at the end is probably not a perfect solution, at least when something like zplug is used? It seemed to have been working, though, until recently (I did one of the occasional updates of zplug today and then the problem occurred).

**Comment by ninrod** [comment]
@osdf you are welcome. That's what I thought. I think that at some point @b4b4r07 commited a change in `enhancd` in that he picks up information about the user filter in "loading time" instead of  "executing time". Which if fine. But maybe he could recheck if filter is present if `enhancd` did not pick anything on loading time? Seems reasonable to me.

**Comment by iladin** [comment]
This looks like a bug

if we take a look [here](https://github.com/b4b4r07/enhancd/blob/master/src/enhancd.sh#L264)  

we can see that it looks to see if $_ENHANCD_FILTER isn't empty but echos that $ENHANCD_FILTER is invalid. It should say something like  "_ENHANCD_FILTER is unset".

_ENHANCD_FILTER is set [here](https://github.com/b4b4r07/enhancd/blob/master/init.sh#L51) with the __enhancd::utils::available function

So I would look there to see whats going on.

**Comment by iladin** [comment]
Fixed for me. I had fzf-tmux in my path that was throwing an error due to an older version of tmux in my path. Removing fzf-tmux fixed the problem for me.

It might be possible to change __enhancd::utils::has to eval the $1 and check the exit code but I think I might submit a PR to fzf-tmux to have it failback on fzf when tmux throws a bad exit code.

Anyways, probably safe to close this.

**Comment by b4b4r07** [comment]
Oops. I missed this issue inadvertently. Please hold while I look it up.
