### ISSUE TITLE
have an option to make `cd -2`do the original behavior

### ISSUE THREAD

**Issue by leomao** [b4b4r07/enhancd#39]
I found #37 and I think it would be nice if `cd -2` have the original behavior.

**Comment by b4b4r07** [comment]
Thanks. Get off my butt!

**Comment by b4b4r07** [comment]
Meged, and thank you your contribution.

**Comment by leomao** [comment]
But I think `cd -2` still doesn't work?

**Comment by b4b4r07** [comment]
I got it but there is no this feature on bash. If I implement this, it'll become new feature for bash user.

**Comment by leomao** [comment]
Oh, I see.

Hmm... I think this is a handy feature.
And I think it will not affect bash users because bash users will never use `cd -2`?

**Comment by b4b4r07** [comment]
Hi, I have added new sources/options now. Please try `back-to-previous` branch.

**Comment by leomao** [comment]
I have tried it.
It doesn't work like the original behavior (dir stack), but I think it is great.

**Comment by b4b4r07** [comment]
I see. 

>but I think it is great.

Glad to hear.

`enhancd` supports custom user-defined option. If you don't like this behavior, you can change or add new options.
