### ISSUE TITLE
Antigen bundle stopped working

### ISSUE THREAD

**Issue by ilkka** [b4b4r07/enhancd#46]
Hi,

Some recent upgrade of either antigen or enhancd caused it to stop working in my setup. When I delete `~/.antigen/repos/*` and `~/.antigen/.cache` and reinstall the bundle, the next shell I start has `cd` aliased to `__enhancd::cd` but it hangs without producing any output. Any shells after that do not have `cd` aliased to anything.

**Comment by b4b4r07** [comment]
Hi, I have tried once or twice but I can't reproduce it. Once again please!

**Comment by milipili** [comment]
I've tried with the latest version of `antigen` and `enhancd` under latest debian testing and nothing works...
But make test works..
```
Test Summary Report
-------------------
All tests successful.
Files=7, Tests=6, Successes=6, Failures=0
Result: PASS

```
zsh 5.2 (x86_64-debian-linux-gnu)

**Comment by milipili** [comment]
Oups sorry my bad. Actually it works. Just it seems that zsh takes over the plugin (no live completion or anything)

**Comment by b4b4r07** [comment]
Did you solve all problems?

**Comment by milipili** [comment]
Sorry I removed it. either it does not work as expected either I have no idea on how to reproduce the behavior like shown on the gif

**Comment by ilkka** [comment]
Whoops, my problem disappeared at some point but I forgot to update the issue. So, no more problems for me 👍🏻

**Comment by shakedlokits** [comment]
I have the same issue, aliased properly `cd: aliased to __enhancd::cd` but does not produce any output. System: `Darwin slokits-iMac 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`
