### ISSUE TITLE
Invalid value as ENHANCD_FILTER over ssh

### ISSUE THREAD

**Issue by xuhdev** [b4b4r07/enhancd#47]
When I run `cd` on a remote system over ssh, I got the following error

    fzf-tmux:fzf:peco:fzy:percol:gof:pick:icepick:sentaku:selecta: Invalid value as ENHANCD_FILTER

No error when I run locally on the same system. `which fzf` gives the path to `fzf` correctly.

**Comment by b4b4r07** [comment]
Thank you for reporting. What the shell have you run on?

**Comment by b4b4r07** [comment]
I just pushed `fix-enhancd-filter` branch. Please try it out

**Comment by xuhdev** [comment]
That fixed the problem. Thanks!
