### ISSUE TITLE
enhancd.log not excluded via .gitignore

### ISSUE THREAD

**Issue by floriankessler** [b4b4r07/enhancd#52]
Hi,

any reason why 'enhancd.log' is not excluded via .gitignore?
Because it's default path is within the git repo...

Thanks, Florian

**Comment by b4b4r07** [comment]
Really? That default path is `$HOME/.enhancd/enhancd.log`

**Comment by floriankessler** [comment]
Thanks for getting back to me. I'm so sorry!

I keep my home organised with git and git sub-modules. And guess where I cloned the enhancd repo to... <wait for it> .... Right! Into ~/.enhancd.
So using your great software it creates a log in the default path, which happens to be the place I checked out the repo, which leads to an unclean git status, which ...

Thanks for pulling my head out of my ...
Florian
