### ISSUE TITLE
Installing requirements with Homebrew (macOS/OS X)

### ISSUE THREAD

**Issue by christopheranderton** [b4b4r07/enhancd#58]
Short instruction for those on macOS/OS X (_tested on OS X 10.11.6_) using Bash.
Not an CLI expert, so there is most likely better ways to do this, or i got it wrong. But i got me up and running. 

### Requirements (using Homebrew and Bash)
**Homebrew:** https://brew.sh/

#### Basic install

```
# add the fzy brew tap to homebrew
$ brew tap jhawthorn/fzy

# install fzy and ccat with homebrew
$ brew install fzy ccat 

# alt: brew install fzy ccat percol peco fzf 
#  depending on which interactive filter you want to use

# install enhancd into your home directory (or a preferred directory)
$ cd ~  
$ git clone https://github.com/b4b4r07/enhancd

# if you want to hide the directory in the finder (gui)
$ chflags hidden enhancd  

# add enhancd to your bash profile (or sourced file of choice)
$ echo "source ~/enhancd/init.sh"  >> ~/.bash_profile

# reload your bash profile
$ source ~/.bash_profile
```

**Comment by b4b4r07** [comment]
Sorry for late. Please explain more what I should do. Should I describe the way to install the dependencies in README?

**Comment by shakedlokits** [comment]
At least add his instructions to:
```shell
# add the fzy brew tap to homebrew
$ brew tap jhawthorn/fzy

# install fzy and ccat with homebrew
$ brew install fzy ccat 
```

Because if you're installing through antigen you don't have those requirements.
This is the 3rd time in the past 2 years I've came to this issue.

Should make this part of the documentation.

**Comment by b4b4r07** [comment]
>Because if you're installing through antigen you don't have those requirements.
>This is the 3rd time in the past 2 years I've came to this issue.
>Should make this part of the documentation.

I'll update readme later

**Comment by b4b4r07** [comment]
@shakedlokits @christopheranderton 

Sorry for late but I submitted the updates about installation guide: https://github.com/b4b4r07/enhancd/pull/86

Please have a look just in case. Thanks

**Comment by b4b4r07** [comment]
Anyway I updated the README based on your suggestions. Please have a look when you have time. Thank you all
