### ISSUE TITLE
cd completion also display files

### ISSUE THREAD

**Issue by qrevel** [b4b4r07/enhancd#66]
Hi,

When enhancd is activated, the cd completion doesn't just select directories but also files.
I did a clean install of zsh on an ubuntu docker container and imported enhancd in it (meaning I don't have any special conf).

```
% whence -v cd
cd is an alias for __enhancd::cd
% echo 'test' > file
% mkdir dir
% cd
dir/  file
```

**Comment by crhg** [comment]
The workaround I am using is to define that completion of `__enhancd::cd` is the same as that of `cd`.

```zsh
compdef __enhancd::cd=cd
```

**Comment by qrevel** [comment]
Thanks. The workaround is working but I'm letting this issue open as it should be included with enhancd

**Comment by b4b4r07** [comment]
Sorry for the late reply.

@qrevel What is your shell?

**Comment by qrevel** [comment]
I'm using zsh

**Comment by b4b4r07** [comment]
I added that function to `init.sh`. Thank you for your suggestion
