### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by kamontat** [b4b4r07/enhancd#67]
<img width="1010" alt="screen shot 2018-05-06 at 15 36 22" src="https://user-images.githubusercontent.com/14089557/39672500-47c368ec-5155-11e8-8c7a-9a24d6dff853.png">

**Comment by HaleTom** [comment]
See #70 for a way to get debug info on what's going on.

**Comment by b4b4r07** [comment]
Sorry for the late reply...

#70 was finally merged. So maybe this problem has been fixed.
