### ISSUE TITLE
Support cd -P and other builtin command options

### ISSUE THREAD

**Issue by HaleTom** [b4b4r07/enhancd#75]
**What did you expect to happen?**
I can use the command-line options of the builtin cd command.  `$PWD` is changed with no output.:
```
% builtin cd -P -- bin
%
```

**What actually happened?**
```
% cd -P -- bin
-P: no such option
```

**Additional context**
The `--` or "end of options should also be supported to cover the edge case where a directory is called `-P` or `-`.

Arguments of the shell's builtin `cd` should be collected and then passed to the underlying builtin command:

`bash`: `cd [-L|[-P [-e]] [-@]] [dir]`
`zsh`: `cd [ -qsLP ] [ arg ]`

**Comment by b4b4r07** [comment]
OK, I will improve it to work just like the default cd command

**Comment by HaleTom** [comment]
Dear robot, is there a way to disable you?

**Comment by ibnishak** [comment]
Please reopen this issue

**Comment by b4b4r07** [comment]
@HaleTom @ibnishak 

Sorry for late response...

I added the feature of supporting builtin option in #88

**Comment by HaleTom** [comment]
Excellent! Thanks very much!

**Comment by gipert** [comment]
Hi! Sorry for necrobumping, but how do I pass `-P` to `cd` by default? I've tried with `export ENHANCD_COMMAND='cp -P'` but no luck...
