### ISSUE TITLE
What happened to the fisherman version?

### ISSUE THREAD

**Issue by patrickf3139** [b4b4r07/enhancd#83]
**Question**
I really want to use enhancd but I use the fish shell. So I looked through issues for "fish" and realized that a while ago, fish support got split into a fisherman package. Unfortunately, the link to that package is broken. Any idea where I can find that repo? Thanks!

**Comment by b4b4r07** [comment]
Thank you for opening issue! And sorry for late response...

Now I have no plan to provide fish version because I'm not familiar with fish shell.. So if fisherman community member can provide it, I'm so happy. Thanks.
