### ISSUE TITLE
Cannot make it work with zplug

### ISSUE THREAD

**Issue by dbenfouzari** [b4b4r07/enhancd#84]
**What did you expect to happen?**
It should correctly load enhancd and give me the custom `cd` command

**What actually happened?**
Just nothing, it looks like `enhancd` won't load

**Output**
```bash
Last login: Wed Dec 12 11:52:06 on ttys008
[zplug] Loaded from cache (/Users/xxxxxx/.zplug/cache)
 Load "~/.zplug/repos/b4b4r07/enhancd/init.sh" (b4b4r07/enhancd)
[zplug] Run compinit
MacBook-Pro-de-xxxxxx%
```

**Additional context**
Here is my newly created .zshrc :

```zsh
##################################
########## DEPENDENCIES ##########
##################################

# Load zplug
if [ ! -d ~/.zplug ]
then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi
source ~/.zplug/init.zsh

# Let zplug manage zplug updates
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

##################################
############ PLUGINS #############
##################################

zplug "b4b4r07/enhancd", use:init.sh
if zplug check "b4b4r07/enhancd"; then
  #export ENHANCD_FILTER="fzf --height 50% --reverse --ansi --preview 'ls -l {}' --preview-window down"
  export ENHANCD_FILTER="fzf --height 50% --reverse --ansi"
  export ENHANCD_DOT_SHOW_FULLPATH=1
fi

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
  printf "Some plugins need to be installed. Install plugins? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

# Source plugins and add commands to $PATH
zplug load --verbose
```

Even if I manually do `source ~/.zplug/repos/b4b4r07/enhancd/init.sh` it does not expose the `cd` command.

I'm on macOS Mojave (10.14.1) with zsh 5.6.2 (x86_64-apple-darwin18.0.0)

Thanks !

**Comment by dbenfouzari** [comment]
Ok, my bad... I did not install `fzy`...

**Comment by b4b4r07** [comment]
👍

**Comment by captainvera** [comment]
@b4b4r07  I don't want to create a new issue, but this is also happening to me, although I DO have `fzy `  installed (checked and working correctly).

I have no output when sourcing init.sh directly and this the relevant part of my .zshrc:


<img width="466" alt="screenshot 2019-02-05 at 18 07 30" src="https://user-images.githubusercontent.com/5597178/52294321-e9f90d80-2970-11e9-8443-d41fe763ef98.png">

I'm on OSX.

I've run out of ideias, any suggestions 🙁 ?

**Comment by dbenfouzari** [comment]
@captainvera If you put an `else` statement, with something like `echo test`, do you see the test message ?

**Comment by captainvera** [comment]
I put an echo inside the if statement and one outside (on the else like you suggested). The correct one gets print.

Also, I can run the zplug check on the terminal and it finishes without any error code...

I'm kinda puzzled by this

**Comment by dbenfouzari** [comment]
Hm... It seems to be the same as I got... No error, seems to be okay, but nothing happens.

As I said before, I had to install `fzy` before. Then it just did work.

**Comment by captainvera** [comment]
Yeah, but I do have `fzy` installed :/ 

I tested as they suggest in their website: 

<img width="524" alt="screenshot 2019-02-06 at 23 58 19" src="https://user-images.githubusercontent.com/5597178/52382540-928c9780-2a6d-11e9-9558-d8f98326e603.png">

**Comment by rubik16x16** [comment]
> Ok, my bad... I did not install `fzy`...

thanks , thats was my problem.

**Comment by Linux-NDOB** [comment]
> Yeah, but I do have `fzy` installed :/
> 
> I tested as they suggest in their website:
> 
> <img alt="screenshot 2019-02-06 at 23 58 19" width="524" src="https://user-images.githubusercontent.com/5597178/52382540-928c9780-2a6d-11e9-9558-d8f98326e603.png">
