### ISSUE TITLE
cd not displaying filter results from fzf

### ISSUE THREAD

**Issue by ghostbuster91** [b4b4r07/enhancd#87]
First of all this seems to be awesome and thank you in advance for creating that project :)

**What did you expect to happen?**
type `cd <Tab>` and see interactive list of directories provided by fzf

**What actually happened?**
I see original list of directories just like using standard `cd` command.

Any ides how can I debug this?
Here is my zshrc: https://github.com/ghostbuster91/dot-files/blob/zplug/.zshrc

Edit: 
So I noticed that it works when I press enter after typing `cd`, is this a desired behavior? Is there an option to change the action it to `<TAB>` key?

**Comment by b4b4r07** [comment]
Did you install fzf? and did you specify `export ENHANCD_FILTER=fzf` in your rc file?

**Comment by ghostbuster91** [comment]
Yes I have fzf installed. No I haven't specify `ENHANCD_FILTER` variable cause I noticed that it is set by default to `fzy:fzf-tmux:fzf:peco:percol:gof:pick:icepick:sentaku:selecta`.

Like I said it works when:
`cd <enter>`

But doesn't work when:
`cd <tab`

**Comment by b4b4r07** [comment]
Sorry for late response and I got it.

I'll investigate it and fix soon! Please wait a sec

**Comment by b4b4r07** [comment]
@ghostbuster91 

> Sorry for late response and I got it.
> 
> I'll investigate it and fix soon! Please wait a sec

I finally understood your motivation and what you wanted to say!

I tried to use https://github.com/changyuheng/zsh-interactive-cd and I found its <Tab> feature but enhancd doesn't have that feature. So,

>So I noticed that it works when I press enter after typing cd, is this a desired behavior? Is there an option to change the action it to <TAB> key?

I can answer this with yes for now.

> @b4b4r07 Could you point me into some direction how can I change this behavior, so the completion will be listed on key, like it works in https://github.com/changyuheng/zsh-interactive-cd ?

But I can also answer with yes by implementing this feature. I'm interested in this feature, so I'll implement this soon. Please wait for a while!

**Comment by ghostbuster91** [comment]
@b4b4r07 Great, thanks!

**Comment by b4b4r07** [comment]
Done. Please try it and give me feedbacks! Thank you.

**Comment by ghostbuster91** [comment]
Hi @b4b4r07, I tried the latest version and it doesn't work as expected. Maybe we misunderstood each other ;)

But I know now how to show you more precisely what I have in mind. 
If you change L136 from `__enhancd::completion::complete ${tokens[2,${#tokens}]/#\~/$HOME}` to `__enhancd::sources::argument` you will have almost the behavior I want. The issue with that is that when you hit enter after such completion the `enhancd` will fire again.

**Comment by b4b4r07** [comment]
@ghostbuster91 

Ah, I forgot to mention how to enable this feature...

You need to set this before typing Tab key in your command line:

```console
$ export ENHANCD_COMPLETION_BEHAVIOR=history
```
It defaults to `default`. It's previous behavior. If you want to use zsh-interactive-cd's one, please set it to `history` !

Is my understanding correct?

**Comment by eddyg** [comment]
I like the behavior when setting `ENHANCD_COMPLETION_BEHAVIOR=history`. Thanks!

The problem I'm running in to is with the [zsh-auto-suggestions](https://github.com/zsh-users/zsh-autosuggestions) package, which I also really like.

Unfortunately, with the "history" completion behavior, the interactively-selected directory just gets _inserted_ on the command line.

In other words, I type `cd `, and thanks to zsh-auto-suggestions, I see:

> cd _/usr/local/bin_

(where "/usr/local/bin" is in light gray, as a suggestion, based on my history). At this point, I could press `Ctrl-E` to jump to the end and execute that command, if that's what I wanted.

But... if I press `tab` at this point to see a list of recent directories, and select, say, `/home` (via `fzy`), I end up with:

> cd /home//usr/local/bin

and the suggestion portion has become part of the command.
 
Any idea how to avoid this behavior?

**Comment by ghostbuster91** [comment]
For me it only looks like it is going to be appended to command but if you execute this cd command you will see that it worked as supposed (the appended path through auto-completion doesn't affect the command) at least for me. Although it would be great if hadn't been appended at the first place :)

**Comment by b4b4r07** [comment]
@eddyg 

Thank you for using this app! I’m glad to hear that.

About your comment, I’m not sure how to avoid it now... Now I haven’t used zsh-auto-suggestions app. So I cannot say about it.. Anyway I’ll use it and then gonna reproduce your problem when I have time. Please let us know when you find some solutions or something. Thanks
