### ISSUE TITLE
run-in-docker.sh always tries to execute with zgen

### ISSUE THREAD

**Issue by marty-oehme** [b4b4r07/enhancd#89]
**What did you expect to happen?**
Install enhancd through zgen, open a terminal without errors.

**What actually happened?**
The shell tries to run a Dockerfile in whatever directory it is opened. This leads to an error message on each new terminal instance.

**Output**
```text
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/marty/Dockerfile: no such file or directory
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Additional context**
Zgen seems to add any .sh executables in the base directory of a plugin to the files it sources. 
When I manually remove run-in-docker.sh, the error disappears. And indeed, in my zgen init.zsh run-in-docker.sh is automatically sourced. 

That means whenever I open a new terminal instance it tries to build a Dockerfile in the local directory, doesn't find one and complains.

For now, I have manually removed the line sourcing run-in-docker.sh from the zgen initialization file. This temporarily fixes it until zgen updates again or reloads any plugins.

**Comment by b4b4r07** [comment]
Sorry, I'll fix soon

**Comment by b4b4r07** [comment]
Moved to other dir.

**Comment by marty-oehme** [comment]
Thanks, works perfectly again!
