### ISSUE TITLE
Suddenly all cd history was lost (;_;)

### ISSUE THREAD

**Issue by ypresto** [b4b4r07/enhancd#96]
**What did you expect to happen?**
History should not be lost.

**What actually happened?**
All history seems to be lost from enhancd.log file.
I didn't remove it by hand.

**Additional context**
Maybe I `Ctrl+C` after moving directory, and maybe it was triggered at middle of this line, but I have no idea actually what I did...
https://github.com/b4b4r07/enhancd/blob/cf68212e748e15ccc487f6a270111abcb30dd321/src/cd.sh#L115

**Comment by b4b4r07** [comment]
Hmm, OK. I'll think about backup system.

**Comment by b4b4r07** [comment]
aThis has been fixed by #165 so closing! Thank you for the report and sorry for keeping you waiting a long time to solve this.
