### ISSUE TITLE
New fish port

### ISSUE THREAD

**Issue by Gazorby** [b4b4r07/enhancd#98]
I love fish shell but i really missed enhancd when i was on zsh so i've made [a port](https://github.com/Gazorby/enhancd-fish) for fish, as i saw the support was dropped.

It works really the same except piping something to cd (like `ls / | cd`). This is because of how piping works in fish (there are multiple issues about this in fish repo) and as far as i know it can't be easily solved.

**Comment by b4b4r07** [comment]
Nice work!! And thank you for porting to fish. How about migrate them to this repo and being a maintainer for that?

**Comment by Gazorby** [comment]
No problem, I'd be glad to help you on the fish version ;)
You think about migrating the port to a new branch on this repo ?

**Comment by b4b4r07** [comment]
>You think about migrating the port to a new branch on this repo ?

Yeah, you can put `init.fish` at top level of this repo. And then you can put fish code in this repo (dedicated directory for fish port). Almost things about shared resources (e.g. awk code) can be used for zsh/bash version and fish version. Of course, you can be a maintainer for the port.

What do you think?

**Comment by Gazorby** [comment]
Done, I send you a PR, see #99

**Comment by b4b4r07** [comment]
Thank you very much for contributing! Finally enhancd got the fish support. Congrats 🎉 I'm gonna keep to maintain the code. Ofc, you can also do this if you want to!
